### ISSUE TITLE
feat: modernize Helm chart to align with auto-generated Kubernetes manifests

### ISSUE THREAD

**Issue by ullbergm** [ullbergm/startpunkt#151]
## Summary

Update the Helm chart templates to align with the auto-generated Kubernetes manifests produced by Quarkus Kubernetes extension, ensuring consistency between deployment methods and reducing maintenance burden.

## Problem Statement / Motivation

The project currently maintains two parallel deployment approaches:

1. **Auto-generated manifests** (`target/kubernetes/kubernetes.yml`) created by Quarkus during build
2. **Manual Helm chart** (`deploy/kubernetes/charts/startpunkt/`) maintained separately

This creates several issues:

- **Maintenance burden**: Changes to deployment configuration must be applied in two places
- **Drift risk**: Helm chart and auto-generated manifests can become out of sync
- **User confusion**: Users might wonder which deployment method to use
- **Feature gaps**: The Helm chart may be missing features present in auto-generated manifests (or vice versa)

### Current State

**Auto-generated manifests** (produced by Quarkus):
- Generated via `quarkus-kubernetes` extension during `mvnw package`
- Located in `target/kubernetes/kubernetes.yml` and `target/kubernetes/openshift.yml`
- Include: ServiceAccount, ConfigMap (with full `application.yaml`), CRDs (v1alpha1, v1alpha4), RoleBinding, Service, Deployment, ServiceMonitor
- Auto-updated with version info, commit IDs, build timestamps
- Workflow: `.github/workflows/generate-deploy-resources.yml` copies these to `deploy/kubernetes/startpunkt-{jvm,native}.yaml`

**Manual Helm chart**:
- Located in `deploy/kubernetes/charts/startpunkt/`
- Version: 0.9.5 (outdated compared to project version 3.5.0-SNAPSHOT)
- Templates: deployment, service, serviceaccount, rolebinding, crds, ingress, route, pdb, servicemonitor
- Missing: ConfigMap with application.yaml configuration
- Configurable via `values.yaml` with extensive customization options

**Why users need this**:
- Helm provides package management, versioning, and rollback capabilities
- Many organizations standardize on Helm for Kubernetes deployments
- Helm charts enable easier configuration management across environments
- Current workaround is manually applying raw YAML, which lacks Helm benefits

## Proposed Solution

Modernize the Helm chart to leverage Quarkus-generated manifests as the source of truth while maintaining Helm's customization capabilities:

### Approach 1: Helm Post-Processor (Recommended)
Use `quarkus-helm` extension to generate Helm charts from Quarkus manifests:
- Already added as dependency in `pom.xml` (`io.quarkiverse.helm:quarkus-helm:1.2.7`)
- Configured in `application.properties` with `quarkus.helm.name=startpunkt`
- Generate chart during build, then enhance with additional templates (Ingress, Route, PDB)

### Approach 2: Update Manual Templates
Update existing Helm templates to match the structure and defaults of auto-generated manifests:
- Synchronize labels, annotations, and metadata
- Add ConfigMap template with full `application.yaml`
- Update CRD definitions to include v1alpha4
- Align probe configurations
- Match resource defaults

## Technical Context

**Related existing features:**
- Quarkus Kubernetes extension generates manifests automatically
- `quarkus-helm` dependency already present but not actively used
- CI workflow generates deployment YAMLs from Quarkus output
- Manual Helm chart exists but is outdated

**Files to modify:**
- `deploy/kubernetes/charts/startpunkt/Chart.yaml` - Update version to match project version
- `deploy/kubernetes/charts/startpunkt/values.yaml` - Add missing configuration options
- `deploy/kubernetes/charts/startpunkt/templates/deployment.yaml` - Sync with Quarkus output
- `deploy/kubernetes/charts/startpunkt/templates/serviceaccount.yaml` - Add Quarkus annotations
- `deploy/kubernetes/charts/startpunkt/templates/service.yaml` - Align with auto-generated
- `src/main/resources/application.properties` - Configure quarkus-helm if using Approach 1
- `.github/workflows/generate-deploy-resources.yml` - Update to generate Helm chart

**Files to create:**
- `deploy/kubernetes/charts/startpunkt/templates/configmap.yaml` - Application configuration
- `docs/deployment/helm-installation.md` - Helm deployment guide

**Configuration changes:**
- Enable Helm generation in Quarkus properties
- Add Helm-specific configuration values
- Ensure backward compatibility with existing deployments

**Dependencies:**
- `io.quarkiverse.helm:quarkus-helm:1.2.7` (already present)
- Quarkus Kubernetes extension (already present)

### Chart Structure
- [ ] Helm chart version matches project version (3.5.x)
- [ ] Chart templates generate manifests equivalent to Quarkus output
- [ ] All Quarkus-generated resources are templated (ServiceAccount, ConfigMap, CRDs, RoleBinding, Service, Deployment, ServiceMonitor)
- [ ] Chart includes CRDs for both v1alpha1 and v1alpha4 API versions
- [ ] ConfigMap template includes full `application.yaml` configuration

### Metadata & Labels
- [ ] Deployment includes Quarkus standard labels:
  - `app.kubernetes.io/name: startpunkt`
  - `app.kubernetes.io/version: {{ version }}`
  - `app.kubernetes.io/managed-by: quarkus`
- [ ] Annotations include:
  - Prometheus scraping annotations
  - Quarkus version, commit ID, VCS URI, build timestamp
- [ ] Labels match Quarkus conventions for consistency

### Configuration
- [ ] `values.yaml` includes all configuration from auto-generated manifests
- [ ] Application configuration can be overridden via Helm values
- [ ] Namespace selector can be customized
- [ ] Resource integrations (Ingress, OpenShift, Hajimari, Istio, GatewayAPI) are configurable
- [ ] Theme colors and UI settings are customizable
- [ ] Image name and tag are parameterized
- [ ] Resource limits and requests are configurable

### Deployment Features
- [ ] Health probes (liveness, readiness, startup) match Quarkus defaults
- [ ] Service exposes port 8080 with targetPort 80 (or configurable)
- [ ] ServiceAccount has proper RBAC (view role binding)
- [ ] ServiceMonitor is included for Prometheus integration
- [ ] Pod Disruption Budget template exists
- [ ] Ingress and Route templates support both Kubernetes and OpenShift

### Testing & Validation
- [ ] Chart can be installed via: `helm install startpunkt ./deploy/kubernetes/charts/startpunkt`
- [ ] `helm template` generates valid Kubernetes manifests
- [ ] Chart passes `helm lint` without errors
- [ ] Deployed application starts successfully and serves UI
- [ ] Health endpoints respond correctly
- [ ] RBAC permissions allow reading cluster resources
- [ ] ConfigMap is properly mounted and configuration is applied

### Documentation
- [ ] README in chart directory explains installation and configuration
- [ ] `values.yaml` is fully documented with comments
- [ ] Deployment guide includes Helm installation steps
- [ ] Examples provided for common configurations (namespace isolation, resource limits, ingress)
- [ ] Migration guide for users currently using raw YAML

### Phase 1: Analyze and Compare
**Estimated effort:** Small (2-3 hours)

**Steps:**
1. Compare auto-generated manifests with Helm chart templates
   ```bash
   # Generate latest manifests
   ./mvnw clean package -DskipTests
   # Compare
   diff -u target/kubernetes/kubernetes.yml deploy/kubernetes/startpunkt-jvm.yaml
   ```

2. Document differences in structure, labels, annotations, and resources:
   - List missing resources (ConfigMap)
   - List outdated versions (Chart.yaml, CRD versions)
   - List missing configuration options
   - Note label/annotation mismatches

3. Create compatibility matrix:
   | Feature | Auto-generated | Helm Chart | Action Needed |
   |---------|---------------|------------|---------------|
   | ServiceAccount | ✅ | ✅ | Sync annotations |
   | ConfigMap | ✅ | ❌ | Add template |
   | CRDs v1alpha4 | ✅ | ❌ | Add to CRD template |
   | ServiceMonitor | ✅ | ✅ | Verify config |
   | Labels/Annotations | Quarkus standard | Custom | Align |

**Testing:**
- No testing required in this phase (analysis only)

### Phase 2: Update Chart Metadata and Structure
**Estimated effort:** Small (2-3 hours)

**Files to modify:**
- `deploy/kubernetes/charts/startpunkt/Chart.yaml`
- `deploy/kubernetes/charts/startpunkt/values.yaml`
- `deploy/kubernetes/charts/startpunkt/README.md`

**Changes to `Chart.yaml`:**
```yaml
---
name: startpunkt
version: 3.5.0  # Match project version
description: Deploy the Startpunkt application - A clean start page for Kubernetes resources
apiVersion: v2
appVersion: "3.5.0"  # Add app version
home: https://github.com/ullbergm/startpunkt
sources:
  - https://github.com/ullbergm/startpunkt
maintainers:
  - name: Magnus Ullberg
    email: ullbergm@gmail.com
keywords:
  - startpage
  - kubernetes
  - dashboard
  - quarkus
```

**Updates to `values.yaml`:**
```yaml
startpunkt:
  labels:
    version: 3.5.0  # Update from 0.9.5
  namespace: default
  image:
    name: ghcr.io/ullbergm/startpunkt  # Change from quay.io
    tag: latest  # or v3.5.0
  
  # Add configuration section matching application.yaml
  config:
    defaultProtocol: "http"
    defaultLanguage: "en-US"
    namespaceSelector:
      any: true
      matchNames: []
    ingress:
      enabled: true
      onlyAnnotated: false
    openshift:
      enabled: true
      onlyAnnotated: false
    hajimari:
      enabled: true
    istio:
      virtualservice:
        enabled: true
        onlyAnnotated: false
    gatewayapi:
      httproute:
        enabled: false
        onlyAnnotated: true
    web:
      title: "Startpunkt"
      githubLink:
        enabled: true
      checkForUpdates: true
      theme:
        light:
          bodyBgColor: "#F8F6F1"
          # ... rest of theme colors
        dark:
          bodyBgColor: "#232530"
          # ... rest of theme colors
  
  # Existing deployment config...
  deployment:
    replicas: 2
    # ...
```

**Testing:**
- Validate YAML syntax
- Run `helm lint deploy/kubernetes/charts/startpunkt`

### Phase 3: Add Missing Templates
**Estimated effort:** Medium (3-4 hours)

**Files to create:**
- `deploy/kubernetes/charts/startpunkt/templates/configmap.yaml`

**ConfigMap Template:**
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    app.openshift.io/vcs-uri: {{ .Values.vcsUri | default "https://github.com/ullbergm/startpunkt" }}
    app.quarkus.io/vcs-uri: {{ .Values.vcsUri | default "https://github.com/ullbergm/startpunkt.git" }}
  labels:
{{ include "startpunkt.labels.chart" . | indent 4 }}
    app.openshift.io/runtime: quarkus
  name: {{ template "startpunkt.name" . }}-config
  namespace: {{ .Values.startpunkt.namespace | default .Release.Namespace }}
data:
  application.yaml: |-
{{ .Values.startpunkt.config | toYaml | indent 4 }}
```

**Files to modify:**
- `deploy/kubernetes/charts/startpunkt/templates/crds.yaml` - Add v1alpha4 CRDs

**CRD Updates:**
Add v1alpha4 versions alongside existing v1alpha1:
```yaml
# Keep existing v1alpha1 definitions
# Add v1alpha4 definitions from target/classes/META-INF/fabric8/
```

**Testing:**
- Generate templates: `helm template startpunkt ./deploy/kubernetes/charts/startpunkt > test-output.yaml`
- Validate YAML syntax
- Compare with auto-generated manifests
- Check for all required resources

### Phase 4: Synchronize Labels and Annotations
**Estimated effort:** Medium (3-4 hours)

**Files to modify:**
- `deploy/kubernetes/charts/startpunkt/templates/_helpers.tpl`
- `deploy/kubernetes/charts/startpunkt/templates/deployment.yaml`
- `deploy/kubernetes/charts/startpunkt/templates/service.yaml`
- `deploy/kubernetes/charts/startpunkt/templates/serviceaccount.yaml`
- `deploy/kubernetes/charts/startpunkt/templates/rolebinding.yaml`

**Update `_helpers.tpl`:**
```tpl
{{- define "startpunkt.labels.quarkus" -}}
app.kubernetes.io/name: {{ template "startpunkt.name" . }}
app.kubernetes.io/version: {{ .Values.startpunkt.labels.version }}
app.kubernetes.io/managed-by: quarkus
app.kubernetes.io/part-of: startpunkt
{{- end -}}

{{- define "startpunkt.annotations.quarkus" -}}
app.quarkus.io/vcs-uri: https://github.com/ullbergm/startpunkt.git
app.openshift.io/vcs-uri: https://github.com/ullbergm/startpunkt
{{- end -}}

{{- define "startpunkt.annotations.prometheus" -}}
prometheus.io/scrape: "true"
prometheus.io/path: /q/metrics
prometheus.io/port: "8080"
prometheus.io/scheme: http
{{- end -}}
```

**Update deployment.yaml:**
```yaml
metadata:
  annotations:
{{ include "startpunkt.annotations.quarkus" . | indent 4 }}
{{ include "startpunkt.annotations.prometheus" . | indent 4 }}
  labels:
{{ include "startpunkt.labels.quarkus" . | indent 4 }}
```

**Update service.yaml:**
Add Prometheus annotations and Quarkus labels

**Update serviceaccount.yaml:**
Add Quarkus annotations for consistency

**Testing:**
- Generate templates and verify labels/annotations
- Check that Prometheus scraping config is correct
- Validate label selectors match

### Phase 5: Integration and CI/CD
**Estimated effort:** Medium (3-4 hours)

**Files to modify:**
- `.github/workflows/generate-deploy-resources.yml`

**Add Helm chart generation step:**
```yaml
- name: Generate Helm chart
  shell: bash
  run: |
    # Option 1: Use quarkus-helm
    ./mvnw package -DskipTests -Dquarkus.helm.enabled=true
    cp -r target/helm/kubernetes/startpunkt/* deploy/kubernetes/charts/startpunkt/
    
    # Option 2: Update existing chart templates
    # Use yq or similar to update values from generated manifests
```

**OR** (if using manual approach):

```yaml
- name: Validate Helm chart
  shell: bash
  run: |
    helm lint deploy/kubernetes/charts/startpunkt
    helm template startpunkt deploy/kubernetes/charts/startpunkt > /tmp/helm-output.yaml
    # Validate generated output
```

**Testing:**
- Run workflow manually
- Verify generated chart is valid
- Check that chart matches auto-generated manifests

### Phase 6: Documentation and Testing
**Estimated effort:** Small (2-3 hours)

**Files to create:**
- `docs/deployment/helm-installation.md`

**Content outline:**
```markdown
# Helm Installation Guide

## Prerequisites
- Helm 3.x installed
- kubectl configured for your cluster
- Appropriate RBAC permissions

## Installation

### Quick Start
helm install startpunkt oci://ghcr.io/ullbergm/startpunkt-helm
# or from local chart
helm install startpunkt ./deploy/kubernetes/charts/startpunkt

### Custom Values
helm install startpunkt ./deploy/kubernetes/charts/startpunkt \
  --set startpunkt.image.tag=v3.5.0 \
  --set startpunkt.config.namespaceSelector.any=false \
  --set startpunkt.config.namespaceSelector.matchNames[0]=default

### Values File
helm install startpunkt ./deploy/kubernetes/charts/startpunkt \
  -f custom-values.yaml

## Configuration Examples

### Limit to specific namespaces
### Custom theme colors
### Resource limits
### Ingress configuration

## Upgrading
helm upgrade startpunkt ./deploy/kubernetes/charts/startpunkt

## Uninstalling
helm uninstall startpunkt

## Troubleshooting
```

**Files to modify:**
- `README.md` - Add Helm installation method
- `deploy/kubernetes/charts/startpunkt/README.md` - Expand documentation
- `deploy/kubernetes/charts/startpunkt/values.yaml` - Add inline comments

**Testing:**
- Install chart in test cluster (KinD or Minikube)
- Verify all resources are created
- Test application functionality
- Verify health endpoints
- Test configuration changes
- Validate upgrade process
- Test uninstall (cleanup)

## Accessibility Requirements

Not applicable - infrastructure tooling.

## Security Considerations

- [ ] ServiceAccount has minimal required permissions (view role only)
- [ ] Pod Security Context can be configured via values
- [ ] Security Context for containers is configurable
- [ ] No secrets hardcoded in chart
- [ ] Default image uses non-root user
- [ ] CRDs include proper validation schemas
- [ ] RBAC follows least privilege principle

## Performance Considerations

- [ ] Default resource requests/limits are reasonable
- [ ] Replica count is configurable
- [ ] Pod Disruption Budget prevents complete outage
- [ ] Health probe settings allow adequate startup time
- [ ] Helm chart generation doesn't slow down build significantly
- [ ] Chart size is reasonable (no embedded binaries)

## Related Issues/PRs

- Related to deployment automation
- Complements auto-generated manifest workflow
- Improves user experience for Helm users

## Open Questions

1. **Should we publish the Helm chart to a repository?**
   - GitHub Pages for chart hosting?
   - OCI registry (ghcr.io)?
   - ArtifactHub listing?

2. **Should we use quarkus-helm or manual templates?**
   - quarkus-helm: Automated but less control
   - Manual: More work but full customization

3. **What's the versioning strategy?**
   - Match project version (3.5.0)?
   - Independent versioning for chart (1.0.0)?
   - Semantic versioning for breaking changes?

4. **Should we maintain both auto-generated YAML and Helm chart?**
   - Keep both for users without Helm?
   - Helm-only with install instructions?
   - Document when to use each approach?

5. **How do we handle CRD lifecycle?**
   - CRDs in chart (problematic with `helm upgrade`)?
   - Separate CRD installation step?
   - Use `helm.sh/hook: crd-install` annotation?

## Out of Scope

- **Helm chart repository hosting**: Initial PR focuses on chart itself
- **ArgoCD/Flux integration**: Can be added in follow-up work
- **Kustomize overlays**: Different deployment approach
- **Migration tooling**: Users can manually switch to Helm
- **Chart hooks for lifecycle management**: Can be added incrementally
- **Subcharts for dependencies**: Startpunkt has no external dependencies
- **Multi-tenant configurations**: Can be handled via multiple releases

---

**Priority:** High  
**Size:** Medium-Large (15-20 hours total)  
**Labels:** enhancement, helm, deployment, documentation
