### ISSUE TITLE
dev: add comprehensive functional testing with native mode support

### ISSUE THREAD

**Issue by ullbergm** [ullbergm/startpunkt#153]
## Summary

Add comprehensive functional testing infrastructure to validate end-to-end application behavior in both JVM and native (GraalVM) modes. This will ensure that Startpunkt works correctly when packaged as a native executable, improving deployment confidence and catching native-specific issues early.

## Problem Statement / Motivation

Currently, Startpunkt has extensive unit tests (`*Test.java`) and integration tests (`*IT.java`), but the integration tests are primarily running in "packaged mode" which still uses the JVM. While the project already has 20 `*IT.java` files extending their corresponding `*Test.java` classes, these tests need to be validated against native builds to ensure:

- **Native Image Compatibility**: Native compilation can expose reflection, serialization, and dynamic loading issues not caught by JVM tests
- **Production Parity**: Native images behave differently than JVM (memory, startup, resource handling)
- **CI/CD Confidence**: The `native-build-test` job in GitHub Actions runs native builds but lacks validation that tests run successfully
- **GraalVM Specific Issues**: Native builds may have runtime issues with Kubernetes client, JSON serialization, and reflective operations

### Current State

✅ **What exists:**
- 20+ integration test files (`*IT.java`) with `@QuarkusIntegrationTest`
- Maven Failsafe plugin configured for integration tests
- Native profile in `pom.xml` with `skipITs=false`
- CI workflow (`native-build-test` job) that builds native images
- Test coverage: 47% instruction, 27% branch

❌ **What's missing:**
- Verification that native mode tests actually run and pass
- End-to-end functional tests validating complete workflows
- Native-specific test scenarios (startup time, memory usage, resource handling)
- Clear documentation on running functional tests locally
- Native mode test execution in CI with proper error reporting

## Proposed Solution

Enhance the existing integration test infrastructure to:

1. **Validate Native Mode Execution**: Ensure all `*IT.java` tests run successfully against native builds
2. **Add Functional Test Scenarios**: Create end-to-end tests that validate complete user workflows
3. **Improve CI Reporting**: Enhance native test job to clearly report test results
4. **Document Testing Procedures**: Add documentation for running and debugging native tests locally

The solution leverages the existing Quarkus test framework and builds upon the established pattern of having `*IT.java` classes extend `*Test.java` classes.

## Technical Context

**Related existing features:**
- 20 integration test files in `src/test/java/us/ullberg/startpunkt/**/*IT.java`
- `@QuarkusIntegrationTest` annotation for packaged mode tests
- Maven Failsafe plugin configured at `pom.xml:406-430`
- Native profile at `pom.xml:662-680`
- GitHub Actions workflow `.github/workflows/build-and-test.yml:91-136`

**Current test structure:**
```
src/test/java/us/ullberg/startpunkt/
├── rest/
│   ├── ApplicationResourceTest.java (unit/integration with @QuarkusTest)
│   ├── ApplicationResourceIT.java (@QuarkusIntegrationTest extends Test)
│   └── (similar pattern for other resources)
├── service/
│   ├── BookmarkServiceTest.java
│   └── (service tests - no IT counterparts yet)
├── health/
│   ├── PingApplicationResourceHealthCheckTest.java
│   ├── PingApplicationResourceHealthCheckIT.java
│   └── (health check ITs exist)
└── crd/
    ├── ApplicationTest.java
    ├── ApplicationIT.java
    └── (CRD model ITs exist)
```

**Files to modify:**
- `.github/workflows/build-and-test.yml` - Enhance native test job reporting
- `pom.xml` - Ensure Failsafe runs with native profile
- `src/test/java/us/ullberg/startpunkt/rest/*IT.java` - Validate existing tests work in native mode

**Files to create:**
- `docs/developer/functional-testing.md` - Documentation for functional testing
- `src/test/java/us/ullberg/startpunkt/functional/NativeStartupIT.java` - Native startup tests
- `src/test/java/us/ullberg/startpunkt/functional/EndToEndWorkflowIT.java` - E2E workflow tests

**Configuration changes:**
- Verify `application.yaml` test profile settings
- Ensure native-image configuration includes test resources

### Native Mode Tests
- [ ] All 20 existing `*IT.java` tests pass when run with `-Pnative`
- [ ] Native build CI job reports test results (not just build success)
- [ ] Native test failures are clearly visible in GitHub Actions
- [ ] Test execution time is monitored and reported

### Functional Test Coverage
- [ ] End-to-end test validates complete application workflow (startup → API calls → response validation)
- [ ] Native-specific tests cover:
  - [ ] Application startup time is reasonable (<5s for native)
  - [ ] Memory footprint is within expected range
  - [ ] Kubernetes client operations work in native mode
  - [ ] JSON serialization/deserialization works
  - [ ] Health checks respond correctly
- [ ] REST endpoints are accessible and return correct data
- [ ] WebSocket connections work in native mode (if applicable)

### Documentation
- [ ] Developer documentation added explaining:
  - [ ] How to run functional tests locally
  - [ ] How to run native mode tests
  - [ ] How to debug native test failures
  - [ ] Common native-specific issues and solutions
- [ ] README.md updated with native testing instructions
- [ ] CI/CD documentation mentions native test requirements

### Quality Assurance
- [ ] Tests run successfully on Linux (primary platform)
- [ ] Test output is clear and actionable
- [ ] No flaky tests introduced
- [ ] Tests complete in reasonable time (native build + tests < 10 minutes)
- [ ] Code coverage remains above current 47% baseline

### Phase 1: Validate and Fix Existing Native Tests
**Estimated effort:** Medium (4-8 hours)

**Files to modify:**
- `pom.xml` (lines 662-680) - Verify native profile configuration

**Steps:**
1. Run existing integration tests in native mode locally:
   ```bash
   ./mvnw clean verify -Pnative -Dquarkus.native.container-build=false
   ```
2. Document any failures and categorize:
   - Reflection issues (add to native-image config)
   - Resource loading issues
   - Kubernetes mock server issues
   - Timing/race conditions
3. Fix identified issues:
   - Add reflection configuration for any missing classes
   - Update test setup for native compatibility
   - Adjust timeouts if needed for native startup
4. Verify all 20 `*IT.java` tests pass:
   - `ApplicationResourceIT`
   - `BookmarkResourceIT`
   - `ConfigResourceIT`
   - `I8nResourceIT`
   - `ThemeResourceIT`
   - All health check ITs (5 files)
   - All CRD model ITs (8 files)
   - All object ITs (2 files)

**Testing:**
- Run each test file individually to isolate issues
- Run full suite to check for interaction issues
- Verify with container-based native build: `-Dquarkus.native.container-build=true`

### Phase 2: Add Native-Specific Functional Tests
**Estimated effort:** Medium (4-6 hours)

**Files to create:**
- `src/test/java/us/ullberg/startpunkt/functional/NativeStartupIT.java`
- `src/test/java/us/ullberg/startpunkt/functional/EndToEndWorkflowIT.java`
- `src/test/java/us/ullberg/startpunkt/functional/NativePerformanceIT.java`

**Structure for `NativeStartupIT.java`:**
```java
@QuarkusIntegrationTest
@TestProfile(NativeStartupIT.NativeProfile.class)
class NativeStartupIT {
  
  @Test
  void testApplicationStartsInNativeMode() {
    // Verify app is running
    given()
      .when().get("/q/health/ready")
      .then().statusCode(200);
  }
  
  @Test
  void testStartupTimeIsReasonable() {
    // Native apps should start in < 5 seconds
    // Test that startup completed quickly
  }
  
  @Test
  void testMemoryFootprint() {
    // Verify native memory usage is lower than JVM
  }
  
  public static class NativeProfile implements QuarkusTestProfile {
    @Override
    public Map<String, String> getConfigOverrides() {
      return Map.of(
        "quarkus.native.enabled", "true",
        "startpunkt.namespaceSelector.any", "true"
      );
    }
  }
}
```

**Structure for `EndToEndWorkflowIT.java`:**
```java
@QuarkusIntegrationTest
@WithKubernetesTestServer
class EndToEndWorkflowIT {
  
  @KubernetesTestServer 
  KubernetesServer server;
  
  @Test
  void testCompleteApplicationWorkflow() {
    // 1. Create Kubernetes resources (Ingress, Route, etc.)
    // 2. Verify applications are discovered
    // 3. Check grouping and sorting
    // 4. Validate JSON response structure
    // 5. Test filtering by tags
  }
  
  @Test
  void testCompleteBookmarkWorkflow() {
    // 1. Create Bookmark CRDs
    // 2. Verify bookmarks are loaded
    // 3. Check grouping and location sorting
    // 4. Validate JSON response
  }
  
  @Test
  void testConfigurationEndpoints() {
    // Test all config endpoints return valid data
  }
}
```

**Testing:**
- Run functional tests in both JVM and native modes
- Verify tests provide meaningful failure messages
- Ensure tests complete in reasonable time

### Phase 3: Enhance CI/CD Native Testing
**Estimated effort:** Small (2-3 hours)

**Files to modify:**
- `.github/workflows/build-and-test.yml` (lines 91-136)

**Changes to `native-build-test` job:**

```yaml
- name: 'build-test-native-java-${{ env.JAVA_VERSION }}'
  working-directory: .
  run: |
    ./mvnw -B -fae clean verify -Pnative \
      -Dquarkus.http.host=0.0.0.0 \
      -Dmaven.compiler.release=${{ env.JAVA_VERSION }} \
      -Dquarkus.native.container-build=false

- name: Upload native test results
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: native-test-results
    path: |
      **/target/surefire-reports/*.xml
      **/target/failsafe-reports/*.xml
    retention-days: 5

- name: Publish JUnit test results to GitHub
  if: always()
  uses: EnricoMi/publish-unit-test-result-action@v2
  with:
    check_name: "Test Results - Native"
    files: |
      **/target/surefire-reports/*.xml
      **/target/failsafe-reports/*.xml
      **/test-results/jest/*.xml

- name: Comment test summary on PR
  if: failure() && github.event_name == 'pull_request'
  uses: actions/github-script@v7
  with:
    script: |
      const fs = require('fs');
      // Parse test results and create summary comment
```

**Testing:**
- Run workflow on a test branch
- Verify test results appear in Actions UI
- Check that failures are reported clearly
- Validate artifacts are uploaded

### Phase 4: Documentation and Polish
**Estimated effort:** Small (2-3 hours)

**Files to create:**
- `docs/developer/functional-testing.md`

**Content outline:**
```markdown
# Functional Testing Guide

## Overview
Explanation of functional vs. unit vs. integration tests

## Running Functional Tests

### JVM Mode
./mvnw verify

### Native Mode (Local)
./mvnw verify -Pnative -Dquarkus.native.container-build=false

### Native Mode (Container Build)
./mvnw verify -Pnative -Dquarkus.native.container-build=true

## Debugging Native Test Failures

### Common Issues
- Reflection issues
- Resource loading
- Timing issues

### Solutions
- Adding to native-image config
- Adjusting test setup
- Using test profiles

## Writing Functional Tests

### Pattern for *IT.java files
### Using @QuarkusIntegrationTest
### Test profiles for native mode
### Best practices
```

**Files to modify:**
- `README.md` - Add "Running Native Tests" section
- `.github/copilot-instructions.md` - Add functional testing guidelines

**Testing:**
- Review documentation for clarity
- Validate all commands work
- Ensure examples are accurate

## Accessibility Requirements

Not applicable - backend testing infrastructure.

## Security Considerations

- [ ] Test execution does not expose secrets or credentials
- [ ] Native builds do not include test code in production images
- [ ] Kubernetes test server properly isolated in tests
- [ ] No hardcoded URLs or credentials in functional tests

## Performance Considerations

- [ ] Native test suite completes in < 10 minutes total
- [ ] Individual test timeouts set appropriately
- [ ] Resource cleanup after tests to prevent memory leaks
- [ ] Parallel test execution where possible
- [ ] CI cache strategy for native builds optimized

## Related Issues/PRs

- Relates to test coverage goals in `docs/TEST_COVERAGE_IMPROVEMENT_PLAN.md`
- Complements existing integration test infrastructure

## Open Questions

1. Should we add native-specific system property tests (e.g., `native.image.path`)?
2. Do we need separate test profiles for container vs. local native builds?
3. Should functional tests be run on every commit or only on main/release branches?
4. What's the acceptable timeout for native build + test in CI (currently ~7-8 minutes)?

## Out of Scope

- **E2E browser testing**: Frontend testing remains with Jest + Testing Library
- **Load/performance testing**: Beyond the scope of functional validation
- **Cross-platform native builds**: Focus on Linux x64 (primary deployment target)
- **Legacy API versions**: v1alpha2 and v1alpha3 are deprecated and untested
- **Service-level integration tests**: Focus is on packaged application behavior, not adding `*IT.java` for services without existing ones

---

**Priority:** Medium  
**Size:** Medium (12-18 hours total)  
**Labels:** enhancement, testing, native
